Repository akretion/sale-import, pull requests merged in 2025-02, with the labels that each got.

#96 chore: update copier
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .ruff.toml
Labels: needs review

#92 [14.0] [FIX] fixes button_open_bindings returned action with proper sale_cha…
  sale_channel_partner/models/sale_channel.py
Labels: bot is merging ⏳, needs review, approved, ready to merge

#91 [14.0] [ IMP] sale_import_base make adresses archiving configurable
  sale_import_base/components/importer_sale_channel.py
  sale_import_base/models/sale_channel.py
  sale_import_base/tests/test_sale_order_import.py
  sale_import_base/views/sale_channel.xml
Labels: bot is merging ⏳, needs review
